/** Logo asset paths for the brand slider (public/ or bundled) */
export const brandLogoPaths: Record<string, { src: string; ext: "png" | "svg" }> = {
  "Ray-Ban": { src: "/logos/brands/ray-ban.png", ext: "png" },
  Oakley: { src: "/logos/brands/oakley.png", ext: "png" },
  Gucci: { src: "/logos/brands/gucci.png", ext: "png" },
  Prada: { src: "/logos/brands/prada.png", ext: "png" },
  "Tom Ford": { src: "/logos/brands/tom-ford.svg", ext: "svg" },
  Versace: { src: "/logos/brands/versace.png", ext: "png" },
  "Dolce & Gabbana": { src: "/logos/brands/dolce-gabbana.png", ext: "png" },
  "Armani Exchange": { src: "/logos/brands/armani-exchange.png", ext: "png" },
  "Calvin Klein": { src: "/logos/brands/calvin-klein.png", ext: "png" },
  "Michael Kors": { src: "/logos/brands/michael-kors.png", ext: "png" },
  Polaroid: { src: "/logos/brands/polaroid.png", ext: "png" },
  Persol: { src: "/logos/brands/persol.png", ext: "png" },
  Silhouette: { src: "/logos/brands/silhouette.png", ext: "png" },
  Carrera: { src: "/logos/brands/carrera.svg", ext: "svg" },
  Police: { src: "/logos/brands/police.svg", ext: "svg" },
  Swarovski: { src: "/logos/brands/swarovski.png", ext: "png" },
  Stepper: { src: "/logos/brands/stepper.svg", ext: "svg" },
  Safilo: { src: "/logos/brands/safilo.png", ext: "png" },
  Vogue: { src: "/logos/brands/vogue.png", ext: "png" },
};
